apiVersion: v1
kind: Service
metadata:
  labels:
    app: cicd-test
  name: cicd-test
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cicd-test
  type: NodePort

