steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/citric-kit-430408-u6/cicd-test/production",
        "-f",
        "./Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/citric-kit-430408-u6/cicd-test/production",
      ]

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE if you do not need logging
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
